### ISSUE TITLE
Make nvidia-container-runtime an empty (meta) package that depends on nvidia-container-toolkit

### ISSUE THREAD

**Issue by kiendang** [julie-is-late/aur-nvidia-container-toolkit#10]
So I looked a bit deeper into the `nvidia-container-runtime` situation. As you know a while ago the `nvidia-container-runtime` executable was migrated into the `nvidia-container-toolkit` repo. What we have been doing is keeping both packages then basically building `nvidia-container-toolkit` repo twice, only installing the `nvidia-ctk` executable in the `nvidia-container-toolkit` package and the `nvidia-container-runtime` in the `nvidia-container-runtime` package.

What I think is a better solution, and also what NVIDIA has been doing for their rpm/deb packages is bundling both executables in the `nvidia-container-toolkit` package. The `nvidia-container-runtime` package then is just an empty package that depends on `nvidia-container-toolkit`. See [here](https://github.com/NVIDIA/nvidia-container-runtime/blob/6f328ae638853b5b295deabfa08becc74f7273ef/README.md#migration-notice) and [here](https://github.com/NVIDIA/nvidia-container-runtime/blob/6f328ae638853b5b295deabfa08becc74f7273ef/rpm/SPECS/nvidia-container-runtime.spec).

I think this is better because
- we are following the official rpm/deb packages
- we're not building the same package twice
- it requires less maintenance since we don't have to do anything for the `nvidia-container-runtime` package

There is a `nvidia-container-toolkit` v1.14.0 release coming which would be a good opportunity to apply the changes.
I actually has begun working on this so when the time come I'll push. Let me know what you think.

TODO

- [ ] install the `nvidia-container-runtime` in the `nvidia-container-toolkit` package
- [ ] remove building `nvidia-container-toolkit` in the `nvidia-container-runtime` package and make it depends on `nvidia-container-toolkit>=1.14.0`
- [ ] for `nvidia-docker`, remove `nvidia-container-runtime` and add `nvidia-container-toolkit>=1.14.0` dependency

**Comment by elezar** [comment]
Thanks for creating this @kiendang. As you correctly pointed out, the `nvidia-docker2` and `nvidia-container-runtime` packages are just meta package (or will be with the v1.14.0 release expected next week).  This means that the only relevant packages are:
* `nvidia-container-toolkit` and `nvidia-container-toolkit-base` from the https://github.com/NVIDIA/nvidia-container-toolkit repo
* `libnvidia-container-tools` and `libnvidia-container1` from the https://github.com/NVIDIA/libnvidia-container repo.

As an additional note, the medium term goal would be to remove the dependency on  the `libnvidia-container*` components, with only the `nvidia-container-toolkit-base` package being required. We also see the `nvidia-container-runtime` and `nvidia-docker2` packages being deprecated -- and if it's simpler, we can do that on AUR first.

As I mentioned to @julie-is-late offline, I'm happy to help out here if I can ramp up on Arch packages and AUR.
